# yazi keymap configuration
# https://yazi-rs.github.io/docs/configuration/keymap

# 選択したファイル/ディレクトリをゴミ箱に移動
#（デフォルトはdだけでゴミ箱行きなので、誤削除防止に２回にする）
[[mgr.prepend_keymap]]
on   = [ "d", "d" ]
run  = "remove"
desc = "ゴミ箱に移動"

# ファイル/ディレクトリのパスをクリップボードにコピー
#（デフォルトはc->c,でファイル、c->dでディレクトリになっており、コマンド別れるのが嫌だったので）
[[mgr.prepend_keymap]]
on   = [ "y", "p" ]
run  = "shell 'printf \"%s\" $0 | pbcopy' --orphan"
desc = "パスをクリップボードにコピー"

# toggle-pane: プレビューペインの表示/非表示
[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane --args=min-preview"
desc = "プレビューペインの表示/非表示"

# toggle-pane: プレビューペインの最大化/復元
[[mgr.prepend_keymap]]
on   = "i"
run  = "plugin toggle-pane --args=max-preview"
desc = "プレビューペインの最大化/復元"
